#!/usr/bin/env python3
"""Tiled JSON(.json/.tmj) map -> mapData.luau / tilesetDefs.generated.luau converter.

Reads a map exported from the Tiled Map Editor (File > Export As > .json) and
writes:
  1. mapData.generated.luau  - generic N-layer tile placement data, consumed by
                                the updated tiles.luau (mapData.layers).
  2. tilesetDefs.generated.luau - one entry per Tiled tileset found in the map,
                                with a REPLACE_ME assetId placeholder (you still
                                have to upload each tileset PNG to Roblox and
                                paste the returned rbxassetid:// yourself, or
                                fill it via the upload_image MCP tool and re-run
                                with --asset-map).

Layer -> ZIndex mapping is controlled by LAYER_ZINDEX below (edit to taste).
Per-tile "canCollide" is read from a Tiled custom bool property named
"canCollide" on the tile (Tileset editor > select tile > Properties > Add
Property > bool). Missing property defaults to False.

Usage:
    python tiled_to_mapdata.py --map path/to/map.json --out-dir <SpriteDemo>/src/client/modules/Town
    python tiled_to_mapdata.py --map map.json --out-dir . --asset-map assets.json

--asset-map is an optional JSON file: {"<tiled-tileset-name>": "rbxassetid://123..."}
which fills in real assetIds instead of REPLACE_ME placeholders.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Layer name (case-insensitive) -> ZIndex. Anything not listed falls back to
# DEFAULT_ZINDEX, incrementing per unmapped layer so ordering is still stable.
LAYER_ZINDEX: dict[str, int] = {
    "background": 0,
    "ground": 1,
    "decor": 5,
    "foreground": 20,
}
DEFAULT_ZINDEX = 5


def load_map(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_asset_map(path: Path | None) -> dict[str, str]:
    if not path:
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def tileset_for_gid(tilesets: list[dict[str, Any]], gid: int) -> tuple[dict[str, Any], int]:
    """Return (tileset_dict, local_index) for a global tile id."""
    chosen = None
    for ts in tilesets:
        if ts["firstgid"] <= gid:
            if chosen is None or ts["firstgid"] > chosen["firstgid"]:
                chosen = ts
    if chosen is None:
        raise ValueError(f"gid {gid} matches no tileset (firstgid table empty?)")
    return chosen, gid - chosen["firstgid"]


def tile_can_collide(tileset: dict[str, Any], local_index: int) -> bool:
    for tiledef in tileset.get("tiles", []):
        if tiledef.get("id") == local_index:
            for prop in tiledef.get("properties", []):
                if prop.get("name") == "canCollide":
                    return bool(prop.get("value"))
    return False


def lua_bool(v: bool) -> str:
    return "true" if v else "false"


def lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_tilesetdefs(tilesets: list[dict[str, Any]], asset_map: dict[str, str]) -> str:
    lines = ["-- AUTO-GENERATED by tools/tiled_to_mapdata.py — do not hand-edit.",
             "-- Fill in real rbxassetid:// values (REPLACE_ME placeholders) after",
             "-- uploading each tileset PNG to Roblox, or re-run with --asset-map.",
             "return {"]
    for ts in tilesets:
        name = ts["name"]
        asset_id = asset_map.get(name, f"REPLACE_ME_{name}")
        tw = ts.get("tilewidth", ts.get("width"))
        th = ts.get("tileheight", ts.get("height"))
        columns = ts.get("columns", 1)
        tilecount = ts.get("tilecount", columns)
        lines.append(f"\t{name} = {{")
        lines.append(f"\t\tassetId = {lua_str(asset_id)},")
        lines.append(f"\t\tcellWidth = {tw},")
        lines.append(f"\t\tcellHeight = {th},")
        lines.append(f"\t\tcolumns = {columns},  -- multi-row offset math in tiles.luau needs this")
        lines.append("\t\ttiles = {")
        for i in range(tilecount):
            lines.append(f"\t\t\ttile{i} = {i},")
        lines.append("\t\t},")
        lines.append("\t},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_mapdata(map_json: dict[str, Any]) -> str:
    tilesets = map_json["tilesets"]
    tw = map_json["tilewidth"]
    th = map_json["tileheight"]

    lines = ["-- AUTO-GENERATED by tools/tiled_to_mapdata.py — do not hand-edit.",
             "-- Re-export from Tiled and re-run the converter instead.",
             "return {",
             "\tground = {},  -- legacy fields kept empty; tiles.luau reads `layers` below",
             "\tdecor = {},",
             "\tlayers = {"]

    for layer in map_json["layers"]:
        if layer.get("type") != "tilelayer":
            continue
        name = layer["name"]
        z_index = LAYER_ZINDEX.get(name.lower(), DEFAULT_ZINDEX)
        width = layer["width"]
        data = layer["data"]

        lines.append(f"\t\t{{")
        lines.append(f"\t\t\tname = {lua_str(name)},")
        lines.append(f"\t\t\tzIndex = {z_index},")
        lines.append("\t\t\tentries = {")

        for i, gid in enumerate(data):
            if gid == 0:
                continue
            col = i % width
            row = i // width
            ts, local_index = tileset_for_gid(tilesets, gid)
            can_collide = tile_can_collide(ts, local_index)
            x = col * tw
            y = row * th
            lines.append(
                f"\t\t\t\t{{ tileset = {lua_str(ts['name'])}, tile = {lua_str('tile' + str(local_index))}, "
                f"x = {x}, y = {y}, canCollide = {lua_bool(can_collide)} }},"
            )

        lines.append("\t\t\t},")
        lines.append("\t\t},")

    lines.append("\t},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--map", required=True, type=Path, help="Path to Tiled .json export")
    parser.add_argument("--out-dir", required=True, type=Path, help="Directory to write the two .luau files into")
    parser.add_argument("--asset-map", type=Path, default=None, help="Optional JSON {tilesetName: rbxassetid} map")
    args = parser.parse_args()

    map_json = load_map(args.map)
    asset_map = load_asset_map(args.asset_map)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "mapData.generated.luau").write_text(build_mapdata(map_json), encoding="utf-8")
    (args.out_dir / "tilesetDefs.generated.luau").write_text(
        build_tilesetdefs(map_json["tilesets"], asset_map), encoding="utf-8"
    )

    tileset_names = [ts["name"] for ts in map_json["tilesets"]]
    missing = [n for n in tileset_names if n not in asset_map]
    print(f"wrote {args.out_dir / 'mapData.generated.luau'}")
    print(f"wrote {args.out_dir / 'tilesetDefs.generated.luau'}")
    if missing:
        print("\nAssetId still needed for these tilesets (upload the PNG to Roblox, then either")
        print("hand-edit tilesetDefs.generated.luau or pass --asset-map):")
        for n in missing:
            print(f"  - {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
